source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NotificationManager_Example', :exclusive => true do
  pod "NotificationManager", :path => "../"
  pod 'MPGNotification'
  
end

target 'NotificationManager_Tests', :exclusive => true do
  pod "NotificationManager", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  
end
